"""
refinement2.py
--------------
Uses the Sarvam AI API to refine and polish translations generated by the NLLB model.
Sarvam specializes in Indic languages, making it highly effective for regional nuances.
"""

import os
import json
import requests
from dotenv import load_dotenv

# 1. Load the environment variables from the .env file
load_dotenv()

# 2. Get the API key
api_key = os.environ.get("SARVAM_API_KEY")
if not api_key:
    raise ValueError("⚠️ SARVAM_API_KEY environment variable not set. Please check your .env file.")

# ============================================
# CORE REFINEMENT FUNCTION
# ============================================
def refine_translation_sarvam(original_text: str, draft_translation: str, target_language: str, domain: str) -> str:
    """
    Refines a draft translation using Sarvam AI to fit a specific domain.
    """
    prompt = f"""
You are an expert bilingual translator and a technical localization specialist in the following domain: {domain}.

I have a source text and a draft translation in {target_language}.
Your task is to refine the draft translation so that it uses the correct terminology, tone, and natural phrasing expected by professionals in the {domain} domain. 

Source Text:
"{original_text}"

Draft Translation ({target_language}):
"{draft_translation}"

Provide ONLY the refined {target_language} translation. Do not include any explanations, quotes, introductory text, or markdown blocks. Just the final text.
"""
    
    # Sarvam's standard chat completion endpoint
    url = "https://api.sarvam.ai/chat/completions"
    
    # Sarvam typically uses 'api-subscription-key' for authorization
    headers = {
        "Content-Type": "application/json",
        "api-subscription-key": api_key
    }
    
    payload = {
        "model": "sarvam-1", # Update this if your Sarvam dashboard specifies a different chat model name (e.g., sarvam-2b)
        "messages": [
            {"role": "system", "content": "You are an expert localization engine. Output only the requested text."},
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3, # Low temperature keeps the model focused and prevents hallucination
        "max_tokens": 512
    }

    try:
        response = requests.post(url, headers=headers, json=payload)
        response.raise_for_status() # Raises an error for bad HTTP status codes (e.g., 401 Unauthorized)
        
        data = response.json()
        
        # Extract the text from the standard OpenAI-compatible response structure
        refined_text = data["choices"][0]["message"]["content"].strip()
        
        if not refined_text:
            return draft_translation
            
        return refined_text

    except requests.exceptions.RequestException as e:
        print(f"⚠️ Sarvam API Network Error: {e}")
        # If you get a 401/403, it means the API key is wrong or the endpoint changed
        if response is not None:
            print(f"Response data: {response.text}")
        return draft_translation
    except (KeyError, IndexError) as e:
        print(f"⚠️ Sarvam API Parsing Error: Unexpected response format. {e}")
        return draft_translation

# ============================================
# EXAMPLE USAGE
# ============================================
if __name__ == "__main__":
    test_source = "The server experienced a segfault due to a null pointer dereference."
    test_draft = "सर्वर ने एक शून्य सूचक संदर्भ के कारण एक सेगफॉल्ट का अनुभव किया।" 
    
    target_lang = "Hindi"
    domain_context = "Computer Science and Software Engineering"

    print("=" * 50)
    print("SARVAM TRANSLATION REFINEMENT DEMO")
    print("=" * 50)
    print(f"Original Source : {test_source}")
    print(f"NLLB Draft      : {test_draft}")
    print("-" * 50)
    
    print(f"🔄 Polishing via Sarvam AI for the '{domain_context}' domain...")
    
    refined = refine_translation_sarvam(
        original_text=test_source,
        draft_translation=test_draft,
        target_language=target_lang,
        domain=domain_context
    )
    
    print(f"✅ Refined Output: {refined}")